import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { validateSession } from '@/lib/auth';
import ExcelJS from 'exceljs';

/**
 * GET /api/v1/admin/bookings/export - Export bookings to Excel
 */
export async function GET(request: NextRequest) {
  try {
    const user = await validateSession();
    if (!user) {
      return NextResponse.json(
        { success: false, error: { code: 'UNAUTHORIZED', message: 'Not authenticated' } },
        { status: 401 }
      );
    }

    if (user.highestRole !== 'DEPARTMENT_ADMIN' && user.highestRole !== 'SUPER_ADMIN') {
      return NextResponse.json(
        { success: false, error: { code: 'FORBIDDEN', message: 'Admin access required' } },
        { status: 403 }
      );
    }

    const { searchParams } = new URL(request.url);
    const startDate = searchParams.get('start_date');
    const endDate = searchParams.get('end_date');
    const includeCancelled = searchParams.get('include_cancelled') === 'true';

    const where: Record<string, unknown> = {};

    if (user.highestRole === 'DEPARTMENT_ADMIN') {
      where.departmentId = user.departmentId;
    }

    if (!includeCancelled) {
      where.isCancelled = false;
    }

    if (startDate || endDate) {
      where.bookingDate = {};
      if (startDate) (where.bookingDate as Record<string, unknown>).gte = new Date(startDate);
      if (endDate) (where.bookingDate as Record<string, unknown>).lte = new Date(endDate);
    }

    const bookings = await db.booking.findMany({
      where,
      orderBy: { bookingDate: 'asc' },
      include: {
        user: { select: { email: true, cabFacility: true } },
        costCenter: { select: { name: true, code: true } },
        department: { select: { name: true } },
        changeRequests: { where: { status: 'PENDING' }, take: 1 },
      },
    });

    // Generate Excel
    const workbook = new ExcelJS.Workbook();
    workbook.creator = user.email;
    workbook.created = new Date();

    const sheet = workbook.addWorksheet('Bookings');

    sheet.addRow([`Generated: ${new Date().toISOString()}`]);
    sheet.addRow([`Generated by: ${user.email}`]);
    sheet.addRow([`Filters: Start=${startDate || 'N/A'}, End=${endDate || 'N/A'}`]);
    sheet.addRow([]);

    const headerRow = sheet.addRow([
      'Employee Email',
      'Department',
      'Cost Center',
      'Cab Facility',
      'Booking Date',
      'Booking Type',
      'Pickup Location',
      'Pickup Time',
      'Drop Location',
      'Drop Time',
      'Cancelled',
      'Pending Change',
    ]);

    headerRow.eachCell((cell) => {
      cell.font = { bold: true };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE2E8F0' } };
    });

    for (const booking of bookings) {
      const pendingChange = booking.changeRequests[0];
      sheet.addRow([
        booking.user.email,
        booking.department.name,
        booking.costCenter ? `${booking.costCenter.name} (${booking.costCenter.code})` : '-',
        booking.user.cabFacility,
        booking.bookingDate.toISOString().split('T')[0],
        booking.bookingType,
        booking.pickupLocation || '-',
        booking.pickupTime || '-',
        booking.dropLocation || '-',
        booking.dropTime || '-',
        booking.isCancelled ? 'Yes' : 'No',
        pendingChange ? `${pendingChange.requestedField}: ${pendingChange.requestedValue || 'Cancel'}` : '-',
      ]);
    }

    sheet.columns.forEach((column) => {
      if (column.values) {
        const maxLength = column.values.reduce((max: number, val) => {
          return Math.max(max, val ? String(val).length : 0);
        }, 10);
        column.width = Math.min(maxLength + 2, 40);
      }
    });

    await db.exportLog.create({
      data: {
        generatedBy: user.id,
        filters: JSON.stringify({ startDate, endDate, includeCancelled }),
        rowCount: bookings.length,
      },
    });

    const buffer = await workbook.xlsx.writeBuffer();
    const filename = `bookings-${startDate || 'all'}-${endDate || 'all'}-${Date.now()}.xlsx`;

    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: 'Failed to generate export' } },
      { status: 500 }
    );
  }
}
